# Generated by Django 5.0.6 on 2024-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
