# Generated by Django 5.0.6 on 2024-08-28 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_article_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("title",),
                "permissions": [
                    (
                        "can_change_article_is_published",
                        "Может редактировать статус публикации",
                    ),
                    ("can_change_article_description", "Может редактировать описание"),
                    ("can_change_article_content", "Может редактировать контент"),
                    (
                        "can_change_article_preview_img",
                        "Может редактировать изображение",
                    ),
                    ("can_change_article_slug", "Может редактировать slug"),
                    ("can_delete_article_article", "Может удалять статью"),
                    ("can_create_article_article", "Может создавать статью"),
                ],
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
    ]
