# Generated by Django 5.0.6 on 2024-07-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="manufactured_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата производства"
            ),
        ),
    ]
