# Generated by Django 5.0.6 on 2024-07-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_remove_products_manufactured_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="created_at",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="updated_at",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="Дата изменения"
            ),
        ),
    ]
