# Generated by Django 5.0.6 on 2024-07-15 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_alter_products_created_at_alter_products_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="has_products",
            field=models.BooleanField(default=False, verbose_name="Есть продукты"),
        ),
        migrations.AlterField(
            model_name="products",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.category",
                verbose_name="категория",
            ),
        ),
    ]
