# Generated by Django 5.0.6 on 2024-07-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_category_has_products_alter_products_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="products",
            name="view_count",
            field=models.IntegerField(default=0, verbose_name="Количество просмотров"),
        ),
    ]
