# Generated by Django 5.0.6 on 2024-08-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_products_slug_products_view_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(verbose_name="номер версии")),
                (
                    "name_version",
                    models.CharField(
                        blank=True, max_length=225, null=True, verbose_name="имя версии"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Активна"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="catalog.products",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "версия",
                "verbose_name_plural": "версии",
                "ordering": ("version",),
            },
        ),
    ]
