# Generated by Django 5.0.6 on 2024-08-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_version_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="has_products",
            field=models.BooleanField(verbose_name="Есть продукты"),
        ),
        migrations.AlterField(
            model_name="version",
            name="is_active",
            field=models.BooleanField(verbose_name="Активна"),
        ),
    ]
