# Generated by Django 5.0.6 on 2024-08-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0009_alter_category_has_products_alter_version_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активна"),
        ),
    ]
