# Generated by Django 5.0.6 on 2024-08-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0012_alter_version_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
    ]
